version: '3'
services:
  sut:
    build:
      context: .
      args:
        - AWS_CLI_VERSION=$DOCKER_TAG
    environment:
      - DOCKER_TAG
    working_dir: /opt/code
    volumes:
      - .:/opt/code
    command: ./test.sh
