version: '3.4'
services:
  sut1:
    build:
      context: .
      dockerfile: DockerfileV1
      args:
        - DOCKER_TAG
    environment:
      - DOCKER_TAG
    working_dir: /opt/code
    volumes:
      - .:/opt/code
    command: ./test.sh

  sut2:
    build:
      context: .
      dockerfile: DockerfileV2
      args:
        - DOCKER_TAG
    environment:
      - DOCKER_TAG
    working_dir: /opt/code
    volumes:
      - .:/opt/code
    command: ./test.sh
