version: '3.4'
services:
  version1: &base
    build: &build
      context: .
      dockerfile: DockerfileV1
      args:
        - DOCKER_TAG
    environment:
      - DOCKER_TAG
    working_dir: /opt/code
    volumes:
      - .:/opt/code
    command: ./test.sh

  amazonlinux:
    <<: *base
    build:
      <<: *build
      dockerfile: Dockerfile-amazonlinux

  ubuntu:
    <<: *base
    build:
      <<: *build
      dockerfile: Dockerfile-ubuntu
