FROM ubuntu:latest

ARG DOCKER_TAG

LABEL maintainer="brainstation<brainstation@outlook.com.au>"

ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM"

RUN apt-get update -y > /dev/null \
    && apt-get install -y curl unzip jq > /dev/null

RUN cd /tmp \
    && AARCH=$([[ "$TARGETPLATFORM" -eq "linux/arm64" ]] && echo "aarch64" || echo "x86_64") \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-${AARCH}-${DOCKER_TAG}.zip" -o "awscliv2.zip" \
    && unzip -qq awscliv2.zip \
    && ./aws/install \
    && rm -rf aws \
    && rm awscliv2.zip
