#!/usr/bin/env bash

function join_by { local IFS="$1"; shift; echo "$*"; }

if [[ "$DOCKER_TAG" == "1"* ]] || [[ "$DOCKER_TAG" == "2"* ]]; then
  CUSTOM_TAG=$(join_by . $(echo $DOCKER_TAG | sed -e 's/\./\n/g' | head -n 2))
  docker tag $IMAGE_NAME $DOCKER_REPO:$CUSTOM_TAG
  docker push $DOCKER_REPO:$CUSTOM_TAG

  CUSTOM_TAG=$(echo $DOCKER_TAG | sed -e 's/\./\n/g' | head -n 1)
  docker tag $IMAGE_NAME $DOCKER_REPO:$CUSTOM_TAG
  docker push $DOCKER_REPO:$CUSTOM_TAG
fi

if [[ "$DOCKER_TAG" == "1"* ]]
  docker tag $IMAGE_NAME $DOCKER_REPO:latest
  docker push $DOCKER_REPO:latest
fi
