#!/usr/bin/env bash

if [[ "$DOCKER_TAG" == "1"* ]]; then
  AWSCLI_MAJOR_VERSION="1"
elif [[ "$DOCKER_TAG" == "2"* ]] || [[ "$DOCKER_TAG" == "latest" ]]; then
  AWSCLI_MAJOR_VERSION="2"
fi

docker-compose -f docker-compose.test.yml run --rm "sut$AWSCLI_MAJOR_VERSION"
