name: sync-tags

on:
  schedule:
    - cron: '0 */8 * * *'
  push:
    branches:
      - 'main'

jobs:
  tagV1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find new tags in awscli
        id: awscli_tags
        shell: bash
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          last_tag=$(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | grep '^1' | head -n 1)
          awscli_tags=$(curl https://pypi.org/pypi/awscli/json \
            | jq '.releases' \
            | jq 'to_entries | map({"tag": .key, "time": .value | select(.[0]) | .[0] | .upload_time_iso_8601})' \
            | jq 'sort_by(.time)')
          if [[ -n $last_tag ]]; then
            last_tag_time=$(echo $awscli_tags | jq --arg last_tag $last_tag -r '.[] | select(.tag == $last_tag) | .time')
            new_tags=$(echo $awscli_tags | jq --arg last_tag_time $last_tag_time '[.[] | select(.time > $last_tag_time)]')
          else
            new_tags=$awscli_tags
          fi
          next_tag=$(echo $new_tags | jq -r '.[0] | .tag')
          echo "::set-output name=next_tag::$next_tag"

      - name: Build and Test Docker Image
        shell: bash
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        env:
          DOCKER_TAG: ${{ steps.awscli_tags.outputs.next_tag }}
        run: |
          docker-compose -f docker-compose.test.yml build version1
          docker-compose -f docker-compose.test.yml run --rm version1
          docker-compose -f docker-compose.test.yml down

      - name: Additional Docker Tags
        id: image_tags
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        env:
          DOCKER_TAG: ${{ steps.awscli_tags.outputs.next_tag }}
        shell: bash
        run: |
          MAJOR_TAG=$(echo $DOCKER_TAG | sed -e 's/\./\n/g' | head -n 1)
          echo "::set-output name=major_tag::$MAJOR_TAG"
          function join_by { local IFS="$1"; shift; echo "$*"; }
          MINOR_TAG=$(join_by . $(echo $DOCKER_TAG | sed -e 's/\./\n/g' | head -n 2))
          echo "::set-output name=minor_tag::$MINOR_TAG"

      - name: Set up QEMU
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./DockerfileV1
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            DOCKER_TAG=${{ steps.awscli_tags.outputs.next_tag }}
          tags: |
            brainstation/awscli:${{ steps.awscli_tags.outputs.next_tag }}
            brainstation/awscli:${{ steps.image_tags.outputs.major_tag }}
            brainstation/awscli:${{ steps.image_tags.outputs.minor_tag }}

      - name: Image digest
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Add a new tag
        shell: bash
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        run: |
          next_tag=${{ steps.awscli_tags.outputs.next_tag }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a $next_tag -m "Automatic tag to catch up aws/aws-cli release"

      - name: Push changes
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  tagV2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: code

      - name: My latest tag
        id: myTag
        shell: bash
        run: |
          cd code
          git fetch --depth=1 origin +refs/tags/*:refs/tags/* > /dev/null
          tag=$(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | grep '^2' | head -n 1)
          echo "::set-output name=tag::$tag"

      - name: Checkout to aws/aws-cli
        uses: actions/checkout@v3
        with:
          repository: aws/aws-cli
          path: awscli

      - name: Find latest tags from aws/aws-cli
        id: awscli_tags
        shell: bash
        run: |
          cd awscli
          git fetch --depth=1 origin +refs/tags/*:refs/tags/* > /dev/null
          awscli_tags=$(git for-each-ref --sort=creatordate --format '{"tag":"%(refname:short)", "time":"%(creatordate:iso-strict)"}' refs/tags | jq -s '.' | jq '[.[] | select(.tag | test("^[0-9]+[.][0-9]+[.][0-9]+$"))]')
          last_tag=${{ steps.myTag.outputs.tag }}
          if [[ -n $last_tag ]]; then
            last_tag_time=$(echo $awscli_tags | jq --arg last_tag $last_tag -r '.[] | select(.tag == $last_tag) | .time')
            new_tags=$(echo $awscli_tags | jq --arg last_tag_time $last_tag_time '[.[] | select(.time > $last_tag_time) | select(.tag | test("^2"))]')
          else
            new_tags=$awscli_tags
          fi
          next_tag=$(echo $new_tags | jq -r '.[0] | .tag')
          echo "::set-output name=next_tag::$next_tag"

      - name: Build and Test Docker Image
        shell: bash
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        env:
          DOCKER_TAG: ${{ steps.awscli_tags.outputs.next_tag }}
        run: |
          docker-compose -f code/docker-compose.test.yml build amazonlinux
          docker-compose -f code/docker-compose.test.yml run --rm amazonlinux
          docker-compose -f code/docker-compose.test.yml build ubuntu
          docker-compose -f code/docker-compose.test.yml run --rm ubuntu
          docker-compose -f code/docker-compose.test.yml down

      - name: Additional Docker Tags
        id: image_tags
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        env:
          DOCKER_TAG: ${{ steps.awscli_tags.outputs.next_tag }}
        shell: bash
        run: |
          MAJOR_TAG=$(echo $DOCKER_TAG | sed -e 's/\./\n/g' | head -n 1)
          echo "::set-output name=major_tag::$MAJOR_TAG"
          function join_by { local IFS="$1"; shift; echo "$*"; }
          MINOR_TAG=$(join_by . $(echo $DOCKER_TAG | sed -e 's/\./\n/g' | head -n 2))
          echo "::set-output name=minor_tag::$MINOR_TAG"

      - name: Set up QEMU
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push - amazonlinux
        id: docker_build_amazonlinux
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: docker/build-push-action@v3
        with:
          context: ./code/
          file: ./code/Dockerfile-amazonlinux
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DOCKER_TAG=${{ steps.awscli_tags.outputs.next_tag }}
          tags: |
            brainstation/awscli:${{ steps.awscli_tags.outputs.next_tag }}
            brainstation/awscli:${{ steps.image_tags.outputs.major_tag }}
            brainstation/awscli:${{ steps.image_tags.outputs.minor_tag }}
            brainstation/awscli:${{ steps.awscli_tags.outputs.next_tag }}-amazonlinux
            brainstation/awscli:${{ steps.image_tags.outputs.major_tag }}-amazonlinux
            brainstation/awscli:${{ steps.image_tags.outputs.minor_tag }}-amazonlinux
            brainstation/awscli:latest
            brainstation/awscli:latest-amazonlinux

      - name: Build and push - ubuntu
        id: docker_build_ubuntu
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: docker/build-push-action@v3
        with:
          context: ./code/
          file: ./code/Dockerfile-ubuntu
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            DOCKER_TAG=${{ steps.awscli_tags.outputs.next_tag }}
          tags: |
            brainstation/awscli:${{ steps.awscli_tags.outputs.next_tag }}-ubuntu
            brainstation/awscli:${{ steps.image_tags.outputs.major_tag }}-ubuntu
            brainstation/awscli:${{ steps.image_tags.outputs.minor_tag }}-ubuntu
            brainstation/awscli:latest-ubuntu

      - name: Image digest
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        run: |
          echo "amazonlinux: ${{ steps.docker_build_amazonlinux.outputs.digest }}"
          echo "ubuntu: ${{ steps.docker_build_ubuntu.outputs.digest }}"

      - name: Add a new tag
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        shell: bash
        run: |
          next_tag=${{ steps.awscli_tags.outputs.next_tag }}
          cd code
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a $next_tag -m "Automatic tag to catch up aws/aws-cli release"

      - name: Push changes
        if: ${{ steps.awscli_tags.outputs.next_tag != 'null' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: code
