#!/usr/bin/env bash

function join_by { local IFS="$1"; shift; echo "$*"; }

CUSTOM_TAG=$(join_by . $(echo $DOCKER_TAG | sed -e 's/\./\n/g' | head -n2))
docker tag $IMAGE_NAME $DOCKER_REPO:$CUSTOM_TAG
docker push $DOCKER_REPO:$CUSTOM_TAG

CUSTOM_TAG=$(echo $DOCKER_TAG | sed -e 's/\./\n/g' | head -n1)
docker tag $IMAGE_NAME $DOCKER_REPO:$CUSTOM_TAG
docker push $DOCKER_REPO:$CUSTOM_TAG

docker tag $IMAGE_NAME $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest
